# Generated by Django 3.1.6 on 2021-02-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('task', models.TextField(blank=True)),
                ('reward', models.CharField(max_length=300)),
                ('addedDate', models.DateTimeField(default='2021-02-13')),
                ('dueDate', models.DateTimeField(default='2021-02-13')),
            ],
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
